--------------------------------------------------------
--  File created - Saturday-August-19-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence HIBERNATE_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "TODO_SPRING_BOOT_DB"."HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table TODO_ROLE
--------------------------------------------------------

  CREATE TABLE "TODO_SPRING_BOOT_DB"."TODO_ROLE" 
   (	"ID" NUMBER(10,0), 
	"ROLE" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TODO_USER
--------------------------------------------------------

  CREATE TABLE "TODO_SPRING_BOOT_DB"."TODO_USER" 
   (	"ID" NUMBER(10,0), 
	"IS_ACCOUNT_NON_EXPIRED" NUMBER(1,0), 
	"IS_ACCOUNT_NON_LOCKED" NUMBER(1,0), 
	"IS_CREDENTIALS_NON_EXPIRED" NUMBER(1,0), 
	"IS_ENABLED" NUMBER(1,0), 
	"PASSWORD" VARCHAR2(255 CHAR), 
	"USERNAME" VARCHAR2(255 CHAR), 
	"ROLE_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into TODO_SPRING_BOOT_DB.TODO_ROLE
SET DEFINE OFF;
Insert into TODO_SPRING_BOOT_DB.TODO_ROLE (ID,ROLE) values (1,'ROLE_USER');
REM INSERTING into TODO_SPRING_BOOT_DB.TODO_USER
SET DEFINE OFF;
Insert into TODO_SPRING_BOOT_DB.TODO_USER (ID,IS_ACCOUNT_NON_EXPIRED,IS_ACCOUNT_NON_LOCKED,IS_CREDENTIALS_NON_EXPIRED,IS_ENABLED,PASSWORD,USERNAME,ROLE_ID) values (1,1,1,1,1,'123','Tom',1);
--------------------------------------------------------
--  Constraints for Table TODO_ROLE
--------------------------------------------------------

  ALTER TABLE "TODO_SPRING_BOOT_DB"."TODO_ROLE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TODO_SPRING_BOOT_DB"."TODO_ROLE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TODO_USER
--------------------------------------------------------

  ALTER TABLE "TODO_SPRING_BOOT_DB"."TODO_USER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TODO_SPRING_BOOT_DB"."TODO_USER" MODIFY ("IS_ENABLED" NOT NULL ENABLE);
  ALTER TABLE "TODO_SPRING_BOOT_DB"."TODO_USER" MODIFY ("IS_CREDENTIALS_NON_EXPIRED" NOT NULL ENABLE);
  ALTER TABLE "TODO_SPRING_BOOT_DB"."TODO_USER" MODIFY ("IS_ACCOUNT_NON_LOCKED" NOT NULL ENABLE);
  ALTER TABLE "TODO_SPRING_BOOT_DB"."TODO_USER" MODIFY ("IS_ACCOUNT_NON_EXPIRED" NOT NULL ENABLE);
  ALTER TABLE "TODO_SPRING_BOOT_DB"."TODO_USER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TODO_USER
--------------------------------------------------------

  ALTER TABLE "TODO_SPRING_BOOT_DB"."TODO_USER" ADD CONSTRAINT "FKH2WQR380532Y1GNWWXCNK5U4S" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "TODO_SPRING_BOOT_DB"."TODO_ROLE" ("ID") ENABLE;
